version: 2

models:
  - name: dim_airports
    columns:
      - name: airport_code
        tests:
          - not_null
          - unique

  - name: fact_flights
    columns:
      - name: airline_code
        tests:
          - not_null
      - name: departure_airport_code
        tests:
          - not_null
      - name: arrival_airport_code
        tests:
          - not_null
      - name: flight_number
        tests:
          - not_null